### ISSUE TITLE
I couldn't run

### ISSUE THREAD

**Issue by mehmet-mert** [TimoLin/SpotifyLyrics#2]
I am sorry, when I try to run it [](https://accounts.spotify.com/authorize) opening and says `INVALID_CLIENT: Invalid redirect URI`

And this is program: ```
Using `localhost` as redirect URI without a port. Specify a port (e.g. `localhost:8080`) to allow automatic retrieval of authentication code instead of having to copy and paste the URL your browser is redirected to.

Enter the URL you were redirected to: 
```

**Comment by TimoLin** [comment]
Hi, Mert,
Since Spotify has lyrics now, I didn't use this tool for a long time. I'll have a look at your issue.
Can you provide more information as shown in the following list?

- [ ] I've create an app in [spotify-developer-dashborad](https://developer.spotify.com/dashboard/applications)
- [ ] I've replaced the `client_id` and `client_secret` of that app with my own information.
- [ ] I've installed all requirements.
- [ ] I am using a Premium account.

**Comment by TimoLin** [comment]
## Spotify developer's app
The `client_id` and  `client_secret` are shown in the app like tihs:
![image](https://user-images.githubusercontent.com/7792396/172285640-70c95fe2-0e04-448e-b5b8-49c18c0ecee1.png)
## First run of this program
Open the link in your browser and copy the redirected link to the terminal.
![image](https://user-images.githubusercontent.com/7792396/172285933-74f61da6-c569-4096-868d-c2c536572875.png)

**Comment by mehmet-mert** [comment]
I am grateful for your helping.
I solved some problems about localhost-not starting-

Whatever, but now whenever I try to run I am getting this:
![Addvcsız](https://user-images.githubusercontent.com/73438714/172652241-3f560ad0-d18f-446f-8f8a-655ad27ad21e.png)
:

**Comment by TimoLin** [comment]
Lyrics API `minilyrics` out of date 
=========================
Hi, Mert
This script searches lyrics from `minilyrics`. Although there are many lyrics source website, but `minilyrics` is the one of the few that has synchronized lyrics. Its website `crintsoft.com` may be out of service for now. See [this reddit thread](https://www.reddit.com/r/musicbee/comments/nip8td/is_minilyrics_dead_its_been_3d_or_so_that_it_cant/). 
There are some alternatives, like [musixmatch](https://developer.musixmatch.com/). But this need register and token to use.

**Comment by TimoLin** [comment]
Hi, @mehmet-mert,
I've found a good lyrics source provider [lrc_kit](https://github.com/reteps/lrc_kit). I've pushed the fix. 
If you are still interested in this small project, feel free to pull the fix patches and follow the instructions in the Readme to have a try.
